pull_request_rules:
  - name: Add label after CI passes
    conditions:
      - check-success=lint
    actions:
      label:
        add:
          - lint_pass
  - name: add label 'test_pass'
    conditions:
      - -label=waiting-approval
      - and: &basic-pr
          - -conflict
          - -draft
          - base=master
          - -title~=(?i)\[wip\]
      - or:
          - check-success=lint
      - or:
          - check-success=build
      - or:
          - check-success=test
    actions:
      label:
        add:
          - test_pass
