name: Lint And Build Package

on:
  push:
    branches:
      - main
      - lwj/skip_test
  pull_request:
    branches:
      - main
      - lwj/skip_test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI_PATH: '/root/actions-runner/${{ github.repository }}/${GITHUB_RUN_NUMBER}'

jobs:
  Clone:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[ci skip]')
      && !contains(github.event.head_commit.message, 'skip ci')
      && !contains(github.event.head_commit.message, 'ci skip')
    runs-on: my_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create custom directory
        run: |
          set -ex
          echo ${{ env.CI_PATH }}
          mkdir -p ${{ env.CI_PATH }}

      - name: Clean custom directory
        run: |
          set -ex
          if [ -d "${{ env.CI_PATH }}" ]; then
            rm -rf ${{ env.CI_PATH }}/*
          fi

      - name: Move code to custom directory
        run: |
          set -ex
          echo 1
          mv $GITHUB_WORKSPACE/* ${{ env.CI_PATH }}/

  test:
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.pull_request.title, 'skip ci')"
    runs-on: my_image
    needs: [Clone]
    steps:
      - name: test
        run: |
          cd ${{ env.CI_PATH }}
          pip install pytest
          python -m pytest --lf --last-failed-no-failures=all -v tests/lwj/ 
      

   