name: Lint And Build Package

on:
  push:
    branches:
      - main
      - lwj/skip_test
  pull_request:
    branches:
      - main
      - lwj/skip_test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: my_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  test:
    runs-on: my_image
    steps:
      - name: test
        run: |
          pip install pytest
          python -m pytest --lf --last-failed-no-failures=all -v tests/lwj/ 
      

   