name: LazyLLM ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "**.md"
env:
  CI_PATH: '/home/mnt/platform_ci/GitHub/${{ github.repository }}/${GITHUB_RUN_NUMBER}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  ChargeTests:
    runs-on: ubuntu-latest
    needs: [ Clone ]
    env:
      LAZYLLM_MOONSHOTAI_API_KEY: ${{ secrets.LAZYLLM_MOONSHOTAI_API_KEY2 }}
    steps:
      - name: RunTests
        run: |
          env
          echo $LAZYLLM_MOONSHOTAI_API_KEY
          export PYTHONPATH=$PWD:$PYTHONPATH
          python -m pytest tests/charge_tests/
