name: Upload PyPI And Release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

env:
  POETRY_VERSION: "1.8.3"
  PYTHON_VERSION: "3.10.9"

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          
      - name: Extract tag from ref
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
  
      - name: Update version in pyproject.toml
        run: |
          sed -i "s/^version = \".*\"/version = \"$TAG\"/" pyproject.toml
          echo $TAG
        env:
          TAG: ${{ env.TAG }}
      - name: Install deps
        shell: bash
        run: pip install -e .
      - name: Test import
        working-directory: ${{ vars.RUNNER_TEMP }}
        shell: bash
        run: |
          pwd
          ls
          python -c "import lazyllm" && cp LazyLLM-Env/poetry.lock .
      - name: Check PyPI for existing version
        id: pypi_check
        run: |
          VERSION=$(poetry version -s)
          poetry version -s
          poetry build
          PACKAGE_NAME=$(poetry version | awk '{print $1}')
          RESPONSE=$(curl -s https://pypi.org/pypi/$PACKAGE_NAME/json)
          if echo "$RESPONSE" | jq -e ".releases | has(\"$VERSION\")"; then
            echo "Version $VERSION already exists on PyPI. Skipping publish."
            echo "pypi_version_exists=true" >> $GITHUB_ENV
          else
            echo "Version $VERSION does not exist on PyPI. Proceeding with publish."
            echo "pypi_version_exists=false" >> $GITHUB_ENV
          fi
     
