name: Test 

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - lwj/test_on_win
  pull_request:
    branches:
      - main

jobs:
  Win_Test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.10.9]

    steps:
      - name: Set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Download model
        run: |
          pip install modelscope yaml
          mkdir /c/Users/runneradmin/.lazyllm
          mkdir -p  /c/Users/runneradmin/.cache/modelscope/hub
          cmd /c mklink /D C:\Users\runneradmin\.lazyllm\model C:\Users\runneradmin\.cache\modelscope\hub
          modelscope download Shanghai_AI_Laboratory/internlm2-chat-7b
          dir /c/Users/runneradmin/.lazyllm
          dir /c/Users/runneradmin/.cache/modelscope/hub
      - name: test command
        run: |
          dir
          whoami
          ls C:\Users\
          mkdir -p /c/Users/runneradmin/.cache/modelscope/hub
