name: Test 

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - lwj/test_on_win
  pull_request:
    branches:
      - main

jobs:
  Win_Test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.10.9]

    steps:
      - name: Set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Download model
        shell: cmd
        run: |
          pip install modelscope pyyaml
          mkdir C:\Users\runneradmin\.lazyllm
          ls C:\Users\runneradmin\.lazyllm
          mkdir C:\Users\runneradmin\.cache\modelscope\hub
          mklink /D C:\Users\runneradmin\.lazyllm\model C:\Users\runneradmin\.cache\modelscope\hub
         
          
      - name: test command
        shell: cmd
        run: |
          cd  C:\Users\runneradmin\.lazyllm
          echo 123 > config.json
          echo "This is an example file" > example.txt
          cd 
          dir
          ls C:\Users\runneradmin\.lazyllm
          cd C:\Users\runneradmin\.lazyllm
          dir
