name: Check File Changes

on:
  push:
    branches:
      - main
      - lwj/test_lint
  pull_request:

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          # 定义一个 filter group，把所有关心的文件放在同一组
          filters: |
            any_changed:
              - 'lazyllm/launcher.py'
              - 'lazyllm/components/deploy/**/*.py'
              - 'lazyllm/module/llms/trainablemodule.py'

  get_changed_env:
    runs-on: ubuntu-latest
    needs: check_changes
    steps:
      - run: echo "IF_CHANGED=${{ needs.check_changes.outputs.changed }}" >> $GITHUB_ENV
             

  AdvancedStandardTests:
    runs-on: ubuntu-latest
    needs: get_changed_env
    steps:
      - name: RunTests
        run: |
          cat $GITHUB_ENV
          if [ "$IF_CHANGED" = "true" ]; then
            echo "目标文件有变化"
          else
            echo "目标文件没有变化"
          fi

  
